### PR TITLE
Add foreign key constraint from measurements to sensors

### PR DESCRIPTION
**Pull request by rnestler**
See #46.

### CODE REVIEW

**Review by dbrgn — APPROVED** [review]

**Comment by rnestler** [comment]
@dbrgn Is the foreign key enough or do you want to enforce `ON DELETE CASCADE` on the DB? I'd leave it as is, since it will now just raise an error if we try to use `delete` instead of `destroy` on the sensor:
```
% ./bin/rails c
Loading development environment (Rails 6.0.6.1)
[1] pry(main)> Sensor.first.delete
  Sensor Load (0.2ms)  SELECT "sensors".* FROM "sensors" ORDER BY "sensors"."id" ASC LIMIT $1  [["LIMIT", 1]]
  Sensor Destroy (0.8ms)  DELETE FROM "sensors" WHERE "sensors"."id" = $1  [["id", 1]]
ActiveRecord::InvalidForeignKey: PG::ForeignKeyViolation: ERROR:  update or delete on table "sensors" violates foreign key constraint "fk_rails_72fe437b01" on table "measurements"
DETAIL:  Key (id)=(1) is still referenced from table "measurements".

from /home/roughl/.asdf/installs/ruby/2.7.7/lib/ruby/gems/2.7.0/gems/activerecord-6.0.6.1/lib/active_record/connection_adapters/postgresql_adapter.rb:675:in `exec_params'
Caused by PG::ForeignKeyViolation: ERROR:  update or delete on table "sensors" violates foreign key constraint "fk_rails_72fe437b01" on table "measurements"
DETAIL:  Key (id)=(1) is still referenced from table "measurements".
```

I'd find it confusing if `delete` acts like destroy.

**Comment by dbrgn** [comment]
I have no idea what the difference between `delete` and `destroy` is 🙂

I'd just like to have a way to delete a sensor along with all measurements. In my view, having measurements in the database without an associated sensor simply doesn't make sense.

(If this is currently the case, then a migration would need to delete those entries first, before being able to apply the new drop constraint.)

**Comment by rnestler** [comment]
> I have no idea what the difference between delete and destroy is :slightly_smiling_face: 

`destroy` will execute lifecycle hooks (like `dependent: :destroy`) recursively, so ensuring everything gets properly destroyed.

So if we don't have any huge performance problems deleting sensors I wouldn't want to circumvent the hooks.

> I'd just like to have a way to delete a sensor along with all measurements. In my view, having measurements in the database without an associated sensor simply doesn't make sense.

If you want to do that manually (for whatever reason) call `destroy` on the sensor in the rails console. Or just use the admin interface.

**Comment by rnestler** [comment]
> (If this is currently the case, then a migration would need to delete those entries first, before being able to apply the new drop constraint.)

I'll delete them manually if they exist (which I don't think).

**Comment by rnestler** [comment]
> I'll delete them manually if they exist (which I don't think).

Just checked, we are all good:
```
irb(main):018:0> Measurement.where.not(sensor_id: Sensor.ids).count
   (1.0ms)  SELECT "sensors"."id" FROM "sensors"
   (43.8ms)  SELECT COUNT(*) FROM "measurements" WHERE "measurements"."sensor_id" NOT IN ($1, $2, $3, $4)  [["sensor_id", 1], ["sensor_id", 6], ["sensor_id", 7], ["sensor_id", 9]]
=> 0
```

**Comment by dbrgn** [comment]
👍🏻

**Pull request merged**
